// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimTro_Backend.Data;

#nullable disable

namespace TimTro_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260712102109_AddRoommateSearchAddress")]
    partial class AddRoommateSearchAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TimTro_Backend.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MaLichHen");

                    b.Property<string>("DiaDiemHen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiLichHen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("NguoiKhoiTaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiKhoiTao");

                    b.Property<Guid>("NguoiNhanHenId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiNhanHen");

                    b.Property<Guid?>("PendingRescheduleById")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RoomPostId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaBaiDangLienKet");

                    b.Property<DateTime>("ThoiGianHen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThaiLichHen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NguoiKhoiTaoId");

                    b.HasIndex("NguoiNhanHenId");

                    b.HasIndex("RoomPostId");

                    b.ToTable("LichHen", (string)null);
                });

            modelBuilder.Entity("TimTro_Backend.Models.MatchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MaYeuCau");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NguoiGuiId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiGui");

                    b.Property<Guid>("NguoiNhanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiNhan");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("NguoiNhanId");

                    b.ToTable("YeuCauGhepNoi", (string)null);
                });

            modelBuilder.Entity("TimTro_Backend.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MaThongBao");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("DaDoc");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiDung");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NoiDung");

                    b.HasKey("Id");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("TimTro_Backend.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MaBaoCao");

                    b.Property<Guid?>("BaiDangBiBaoCaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaBaiDangBiBaoCao");

                    b.Property<string>("DuongDanMinhChung")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("[]")
                        .HasColumnName("DuongDanMinhChung");

                    b.Property<string>("LyDoPhanAnh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayTao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("NguoiGuiId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiGui");

                    b.Property<Guid?>("NguoiKiemDuyetXuLyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiKiemDuyetXuLy");

                    b.Property<Guid?>("TaiKhoanBiBaoCaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaTaiKhoanBiBaoCao");

                    b.Property<string>("TrangThaiXuLy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaiDangBiBaoCaoId");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("NguoiKiemDuyetXuLyId");

                    b.HasIndex("TaiKhoanBiBaoCaoId");

                    b.ToTable("BaoCaoViPham", (string)null);
                });

            modelBuilder.Entity("TimTro_Backend.Models.RoomImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MaHinhAnh");

                    b.Property<string>("DuongDanHinhAnh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaDinhDanhCloudinary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoomPostId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaBaiDang");

                    b.HasKey("Id");

                    b.HasIndex("RoomPostId");

                    b.ToTable("HinhAnhPhongTro", (string)null);
                });

            modelBuilder.Entity("TimTro_Backend.Models.RoomPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MaBaiDang");

                    b.Property<Guid>("ChuTroId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaChuTro");

                    b.Property<string>("DiaChiChiTiet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("KinhDoThucTe")
                        .HasColumnType("double");

                    b.Property<string>("LoaiBaiDang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTaChiTiet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("NguoiDuyetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiDuyet");

                    b.Property<string>("TienIch")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThaiKiemDuyet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThaiPhong")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ViDoThucTe")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ChuTroId");

                    b.HasIndex("NguoiDuyetId");

                    b.ToTable("BaiDangPhongTro", (string)null);
                });

            modelBuilder.Entity("TimTro_Backend.Models.RoommateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MaHoSo");

                    b.Property<int>("BanKinhTimKiemToiDa")
                        .HasColumnType("int");

                    b.Property<string>("DiaChiKhuVuc")
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("longtext");

                    b.Property<string>("GioiTinhMongMuon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("KinhDoMucTieu")
                        .HasColumnType("double");

                    b.Property<double?>("NganSachToiDa")
                        .HasColumnType("double");

                    b.Property<double?>("NganSachToiThieu")
                        .HasColumnType("double");

                    b.Property<string>("TieuChiLoiSong")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiDung");

                    b.Property<double?>("ViDoMucTieu")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HoSoOGhep", (string)null);
                });

            modelBuilder.Entity("TimTro_Backend.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MaGiaoDich");

                    b.Property<string>("LoaiGoi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaQR")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiDung");

                    b.Property<Guid?>("NguoiDuyetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiDuyet");

                    b.Property<string>("NoiDungChuyenKhoan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("NguoiDuyetId");

                    b.ToTable("GiaoDich", (string)null);
                });

            modelBuilder.Entity("TimTro_Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MaNguoiDung");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MatKhauBam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayHetHanDichVu")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TrangThaiTaiKhoan")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("TimTro_Backend.Models.Appointment", b =>
                {
                    b.HasOne("TimTro_Backend.Models.User", "NguoiKhoiTao")
                        .WithMany("CreatedAppointments")
                        .HasForeignKey("NguoiKhoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimTro_Backend.Models.User", "NguoiNhanHen")
                        .WithMany("ReceivedAppointments")
                        .HasForeignKey("NguoiNhanHenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimTro_Backend.Models.RoomPost", "RoomPost")
                        .WithMany("Appointments")
                        .HasForeignKey("RoomPostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiKhoiTao");

                    b.Navigation("NguoiNhanHen");

                    b.Navigation("RoomPost");
                });

            modelBuilder.Entity("TimTro_Backend.Models.MatchRequest", b =>
                {
                    b.HasOne("TimTro_Backend.Models.User", "NguoiGui")
                        .WithMany("SentMatchRequests")
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimTro_Backend.Models.User", "NguoiNhan")
                        .WithMany("ReceivedMatchRequests")
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("TimTro_Backend.Models.Notification", b =>
                {
                    b.HasOne("TimTro_Backend.Models.User", "NguoiDung")
                        .WithMany("Notifications")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("TimTro_Backend.Models.Report", b =>
                {
                    b.HasOne("TimTro_Backend.Models.RoomPost", "BaiDangBiBaoCao")
                        .WithMany("Reports")
                        .HasForeignKey("BaiDangBiBaoCaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimTro_Backend.Models.User", "NguoiGui")
                        .WithMany("SentReports")
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimTro_Backend.Models.User", "NguoiKiemDuyetXuLy")
                        .WithMany("ProcessedReports")
                        .HasForeignKey("NguoiKiemDuyetXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimTro_Backend.Models.User", "TaiKhoanBiBaoCao")
                        .WithMany("ReceivedReports")
                        .HasForeignKey("TaiKhoanBiBaoCaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaiDangBiBaoCao");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiKiemDuyetXuLy");

                    b.Navigation("TaiKhoanBiBaoCao");
                });

            modelBuilder.Entity("TimTro_Backend.Models.RoomImage", b =>
                {
                    b.HasOne("TimTro_Backend.Models.RoomPost", "RoomPost")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomPost");
                });

            modelBuilder.Entity("TimTro_Backend.Models.RoomPost", b =>
                {
                    b.HasOne("TimTro_Backend.Models.User", "ChuTro")
                        .WithMany("RoomPosts")
                        .HasForeignKey("ChuTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimTro_Backend.Models.User", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChuTro");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("TimTro_Backend.Models.RoommateProfile", b =>
                {
                    b.HasOne("TimTro_Backend.Models.User", "User")
                        .WithOne("RoommateProfile")
                        .HasForeignKey("TimTro_Backend.Models.RoommateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimTro_Backend.Models.Transaction", b =>
                {
                    b.HasOne("TimTro_Backend.Models.User", "NguoiDung")
                        .WithMany("Transactions")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimTro_Backend.Models.User", "NguoiDuyet")
                        .WithMany("ProcessedTransactions")
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("TimTro_Backend.Models.RoomPost", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Reports");

                    b.Navigation("RoomImages");
                });

            modelBuilder.Entity("TimTro_Backend.Models.User", b =>
                {
                    b.Navigation("CreatedAppointments");

                    b.Navigation("Notifications");

                    b.Navigation("ProcessedReports");

                    b.Navigation("ProcessedTransactions");

                    b.Navigation("ReceivedAppointments");

                    b.Navigation("ReceivedMatchRequests");

                    b.Navigation("ReceivedReports");

                    b.Navigation("RoomPosts");

                    b.Navigation("RoommateProfile")
                        .IsRequired();

                    b.Navigation("SentMatchRequests");

                    b.Navigation("SentReports");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
